# Generated by Django 4.0.1 on 2022-01-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='email',
            new_name='username',
        ),
    ]
